### PR TITLE
updated node usb native from vscode-arduino repo

### PR DESCRIPTION
**Pull request by andreamah**
# Description:

The CPX serial monitor for deploy to device currently doesn't work, even on the extension published to the VS Code Marketplace. It seemed that the issue was that the code in the ./vendor/ directory was outdated. This code is taken from the vscode-arduino repository and it seems like there was a fix from 3 months ago to fix a bug. Otherwise, that code was untouched for ~ 3yrs.

See here: https://github.com/microsoft/vscode-arduino/tree/master/vendor/node-usb-native

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

# Limitations:

# Testing:

- [ ] Basic serial monitor testing with deploy to device on CPX

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My code has been formatted with `npm run format` and passes the checks in `npm run check`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by andreamah** [comment]
NOTE: this change is just copy+pasting the changes from the vscode-arduino repo (https://github.com/microsoft/vscode-arduino/tree/master/vendor/node-usb-native). Any comments about the code should be directed towards that team 😯

**Review by nasadigital — APPROVED** [review]
LGTM.
Just FYI, if this is a straight copy from the other repository, it might be worth considering using git submodules.

**Review by vandyliu — APPROVED** [review]
good stuff drea

**Comment by vandyliu** [comment]
> LGTM.
> Just FYI, if this is a straight copy from the other repository, it might be worth considering using git submodules.

@nasadigital 
Thanks for the suggestion. From my quick research, it looks like git submodules must have the entire repo "cloned" as a submodule. I'm not sure how viable that would be in this case. What do you think?

**Comment by nasadigital** [comment]
> @nasadigital
> Thanks for the suggestion. From my quick research, it looks like git submodules must have the entire repo "cloned" as a submodule. I'm not sure how viable that would be in this case. What do you think?

Thanks for looking into it!
Makes sense. In that case, I don't have any further suggestion.

**Pull request merged**
