### PR TITLE
Update package.json for marketplace

### PR DESCRIPTION
**Pull request by DonJayamanne**
From the VS Code Python team, adding a link to the repo to add visibility to the source repo on the marketplace.

# Description:

* Looking at the marketplace its not easy to find the source for the repo (its open source, but finding the source is not possible).
This PR will add the link to the repo.
* Searching for this extension is improved with addition of keywords (Adafruit, circuit python and python).

## Type of change
* Updates to the package.json file

Please delete options that are not relevant.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [n/a] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jonathanwangg — COMMENTED** [review]
The additions look great. Can the indentation of the `activationEvents` key be fixed before this PR is approved?

**Review by iennae — CHANGES_REQUESTED** [review]
Can you fix the indentation? Otherwise, this is a great update. Thank you!

**Review by iennae — APPROVED** [review]

**Comment by iennae** [comment]
I've gone ahead and fixed the indentation. Thanks again for the contribution.

**Comment by DonJayamanne** [comment]
Thanks, forgot about this.

**Pull request merged**
