### PR TITLE
Hotfix for users without Git

### PR DESCRIPTION
**Pull request by andreamah**
# Description:
The tarball for adafruit_display_text was having trouble being unzipped for users without git. **I moved the tarball files to the `src/clue` directory so that it doesn't need to be unzipped + installed via pip.**

**label.py was originally within the zipped tarball, but now it is in src/clue/adafruit_display_text/label.py**

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Testing:

Tested on windows on code that uses adafruit_clue and adafruit_display_text.

### CODE REVIEW

**Comment by nasadigital** [comment]
@andreamah How can I build a .vsix to try if it fixes the issue?

**Comment by andreamah** [comment]
> @andreamah How can I build a .vsix to try if it fixes the issue?

I'll create a vsix and send it to you.

**Comment by isadorasophia** [comment]
This definitely sounds okay for a hot fix! Were you able to get repro it or get to the bottom of the underlying issue though? Was it something with a git requirement?

**Comment by andreamah** [comment]
> This definitely sounds okay for a hot fix! Were you able to get repro it or get to the bottom of the underlying issue though? Was it something with a git requirement?

The underlying issue was that users needed Git. Pip installing from a tar.gz file requires Git for some reason

**Review by nasadigital — APPROVED** [review]
LGTM!

**Review by vandyliu — APPROVED** [review]
Tested on windows computer without git!

**Pull request merged**
