### PR TITLE
Removing preview mode

### PR DESCRIPTION
**Pull request by vandyliu**
[AB#34122](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34122)

# Description:
- Removed preview mode setting, so microbit commands show up regardless
- If anyone has a better idea to remove it so that it is easy to add once again (for clue), please let me know

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

# Limitations:

Please describe limitations of this PR

# Testing:

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My code has been formatted with `npm run format` and passes the checks in `npm run check`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by nasadigital — APPROVED** [review]
LGTM.
Are you sure you want to delete preview mode? If you add any new devices, I assume you would first offer them through the preview mode.
You would need to add everything back in that case, right?

**Review by andreamah — APPROVED** [review]
Tested and good! 😎

**Comment by vandyliu** [comment]
> LGTM.
> Are you sure you want to delete preview mode? If you add any new devices, I assume you would first offer them through the preview mode.
> You would need to add everything back in that case, right?

@nasadigital
Yeah, we would have to add everything back. I'm not sure what the best way to do this is. Maybe we can hold off on this until we decide on a release date for sure?

**Comment by nasadigital** [comment]
> @nasadigital
> Yeah, we would have to add everything back. I'm not sure what the best way to do this is. Maybe we can hold off on this until we decide on a release date for sure?

@vandyliu Up to you! Was just curious.

**Pull request merged**
