### PR TITLE
Getting Started Improvements

### PR DESCRIPTION
**Pull request by vandyliu**
[AB#34549](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34549) [AB#34555](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34555) [AB#34552](https://microsoftgarage.visualstudio.com/002806e2-ebaa-4672-9d2e-5fe5d29154ef/_workitems/edit/34552)
# Description:
- Added debugger info on getting started
- Added debugger to dropdown and added categories to dropdown
- Removed bolding on h3 because there was too much boldness
- Added keyboard shortcuts for device on getting started
- Removed preview mode for CLUE getting started
- NEED TO UPDATE PICTURE LINKS FOR DEBUGGER

Debug Page on Getting Started

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Limitations:

Please describe limitations of this PR

# Testing:

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My code has been formatted with `npm run format` and passes the checks in `npm run check`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by andreamah** [comment]
Can you increase the padding at the bottom of the page? It seems like it ends sorta abruptly:
image

**Review by xnkevinnguyen — APPROVED** [review]
LGTM! Merge it once preview mode is removed :)

**Review by andreamah — APPROVED** [review]
Good! Thanks for adding the padding 😎

**Review by nasadigital — APPROVED** [review]
Looks good!

**Pull request merged**
