### PR TITLE
Output dependency installation failures to an output channel

### PR DESCRIPTION
**Pull request by eishan05**
# Description:

This is a fix for issue #157 . When dependency installation from the first-run prompt popup fails, the error log is not shown to the user. With this change, the error log is output to the "Installation Error" output channel in the VS code window, so the user can debug installation issues and get started with the extension quicker.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Testing:

- [ ] Deliberately run an incorrect command in the `installPythonDependencies` method to ensure that the failed command run is being logged to the output channel. 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My code has been formatted with `npm run format` and passes the checks in `npm run check`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by vandyliu — APPROVED** [review]
Awesome 👯‍♂

**Review by xnkevinnguyen — APPROVED** [review]
LGTM

**Review by nasadigital — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
