### PR TITLE
Deploy to Clue and Deploy Command Pallete Refactoring

### PR DESCRIPTION
**Pull request by vandyliu**
# Description:
Deploy to device command
- Added deployment to Adafruit Clue and its corresponding telemetry
- Because Clue and CPX are so similar, I refactored some things to reuse as much code as possible
- Changed commands so that deploy to device is one command (and we don't have one for each device) then when the command is selected, the user can select which device they want.
- Added TelemetryHandlerService to hold all functions that have to do with handling telemetry because there were just a bunch in extension.ts (it removes clutter)
- **Want opinions**: 
   @andreamah @xnkevinnguyen 
   - Do you like this change? If so, I can update it for Open Simulator and New File.
   - Should we have the names of the devices more formal?
        - Eg. instead of `CLUE`, have it as `Adafruit CLUE` 
        - Eg. instead of `CPX`, have it as `Adafruit Circuit Playground Express` or `Circuit Playground Express`
- Will update README once Open Simulator and New File are updated (if they are updated).

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Limitations:

Please describe limitations of this PR

# Testing:

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My code has been formatted with `npm run format` and passes the checks in `npm run check`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by xnkevinnguyen** [comment]
Regarding the commands, It's definitely a good improvement and will reduce the number of commands overall.

**Comment by xnkevinnguyen** [comment]
Agreed with the formal name, Adafruit Clue, Adafruit Circuit Playground Express, BBC micro:bit

**Comment by andreamah** [comment]
Sounds great! I agree with Kevin.

**Review by nasadigital — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
